classDiagram
    class Navio {
        -int codigoNavio
        -String nombreNavio
        -float altura
        -float eslora
        -float manga
        -float desplazamiento
        -float autonomiaViaje
        -int cantidadCamarotes
        -int maxCantidadPasajeros
        -int cantidadMotores
        -int cantidadTripulantes
        -Categoria clasificacion
        -Tripulante listaTripulantes
        -Cubierta listaCubiertas

        +new()
        +conocerTripulantes()
        +conocerEstado()
        +conocerCategoria()
        +conocerCubierta()
        +conocerViaje()
    }

    class Cubierta {
        -int numeroCubierta
        -Ubicacion ubicacionCubierta
        -Encargado encargado
        -String descripcionCubierta
        -Camarote camarote
    
        +new()
        +conocerCamarote()
        +conocerUbicacion()
    }

    class Camarote {
        -TipoCamarote tipoCamarote
        -Ubicacion ubicacionCamarote
        -int numeroCamarote
    
        +new()
        +conocerTipoCamarote()
        +conocerUbicacion()
    }

    class TipoCamarote {
        -String nombreTipoCamarote
        -String descripcionTipoCamarote
    
        +new()
    }

    class Ubicacion {
        -String nombreUbicacion
        -String descripcionUbicacion
    
        +new()
    }

    class Tripulante {
        -String nombreTripulante
        -String legajo
        -Navio navioAsignado
        -Puesto puestoTripulante
        -String nombreJefe
    
        +new()
        +conocerPuerto()
    }

    class Puesto {
        -String nombrePuesto
        -String descripcionPuesto
    
        +new()
    }

    class Viaje {
        -Itinerario itinerarioRealizado
        -Navio navioDelViaje
        -datetime fechaViaje
        -float duracionViaje
        -Pasajero listaPasajerosReservados
        -Pasajero listaPasajerosPresentes
    
        +new()
    }

    class Puerto {
        -String nombrePuerto
        -String descripcionPuerto
    
        +new()
    }

    class Pasajero {
        -String tipoDocumento
        -int numeroDocumento
        -String nombre
        -Pais paisOrigen
        -Ciudad ciudadOrigen
        -Viaje viajeRealizado
        -Camarote camaroteAlojado
    
        +new()
        +conocerPais()
    }

    class Estado {
        -String nobreEstado
        -String descripcionEstado
    
        +new()
    }

    class Categoria {
        -String nombreCategoria
        -String descripcionCategoria
    
        +new()
    }

    class Pais {
        -String nombrePais
        -String descripcionPais
        -String moneda
        -String idioma

        +new()
        +conocerCiudad()

        +setNombrePais()
        +getNombrePais()
        +setDescripcionPais()
        +getDescripcionPais()
        +setMoneda()
        +getMoneda()
        +setIdioma()
        +getIdioma()
    }

    class Ciudad {
        -String nombreCiudad
        -String descripcionCiudad
        -Pais pais

        +new()
    }

    class Itinerario {
        -Puerto listaPuertos
        -int numeroEscala
        -Categoria categoriaItinerario

        +new()
        +conocerNavio()
        +conocerPuerto()
        +conocerCategoria()
    }

    Itinerario --> "1" Navio
    Navio --> "1..*" Viaje
    Tripulante --|> Pasajero
    Camarote --> "1" TipoCamarote
    Navio --> "1..*" Cubierta
    Cubierta --> "1..*" Camarote
    Navio --> "1..*" Tripulante
    Itinerario --> "1" Categoria
    Pasajero --> "1" Pais
    Pasajero --> "1" Ciudad
    Pais --> "1..*" Ciudad
    Navio --> "1" Estado
    Tripulante --> "1" Puesto
    Cubierta --> "1" Ubicacion
    Camarote --> "1" Ubicacion
    Itinerario --> "1..*" Puerto
    Navio --> "1" Categoria
