# Generated by Django 4.2.4 on 2023-09-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camarote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_camarote', models.CharField(max_length=100)),
                ('ubicacion_camarote', models.IntegerField()),
                ('numero_camarote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('descripcion_ciudad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100)),
                ('descripcion_pais', models.TextField()),
                ('moneda', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('descripcion_puesto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tripulante', models.CharField(max_length=100)),
                ('legajo', models.CharField(max_length=10)),
                ('nombre_jefe', models.CharField(max_length=100)),
                ('navio_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.navio')),
                ('puesto_tripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('camarote_alojado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.camarote')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.ciudad')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.pais')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.pais'),
        ),
    ]
