# Generated by Django 4.2.5 on 2023-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0003_cambioestadonavio_categoriaitinerario_categorianavio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='numeroEscala',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='numeroEscala',
            field=models.IntegerField(default=0, verbose_name='Numero Escala'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cubierta',
            name='camarote',
        ),
        migrations.AddField(
            model_name='cubierta',
            name='camarote',
            field=models.ManyToManyField(to='seastar.camarote'),
        ),
    ]
