# Generated by Django 4.2.5 on 2023-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0004_remove_recorrido_numeroescala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='duracionViaje',
            field=models.TimeField(verbose_name='Duración aproximada del viaje'),
        ),
    ]
