# Generated by Django 4.2.5 on 2023-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0005_alter_recorrido_duracionviaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='duracionViaje',
            field=models.FloatField(verbose_name='Duración aproximada del viaje'),
        ),
    ]
