# Generated by Django 4.2.5 on 2023-10-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0006_alter_recorrido_duracionviaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocamarote',
            name='ListaPasajerosOcupandoCamarote',
        ),
        migrations.RemoveField(
            model_name='estadocamarote',
            name='camaroteOcupado',
        ),
        migrations.RemoveField(
            model_name='reservacamarote',
            name='listaCamarotes',
        ),
        migrations.AddField(
            model_name='camarote',
            name='estadoCamarote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seastar.estadocamarote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadocamarote',
            name='nombreEstadoCamarote',
            field=models.CharField(default=1, max_length=255, verbose_name='Estado del Navio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamarote',
            name='ListaPasajerosOcupandoCamarote',
            field=models.ManyToManyField(to='seastar.pasajero'),
        ),
        migrations.AddField(
            model_name='reservacamarote',
            name='camarotesReservado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seastar.camarote'),
            preserve_default=False,
        ),
    ]
