# Generated by Django 4.2.5 on 2023-10-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0007_remove_estadocamarote_listapasajerosocupandocamarote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacamarote',
            old_name='camarotesReservado',
            new_name='camaroteReservado',
        ),
        migrations.RenameField(
            model_name='reservacamarote',
            old_name='ListaPasajerosOcupandoCamarote',
            new_name='listaPasajeros',
        ),
        migrations.RemoveField(
            model_name='estadocamarote',
            name='tripulanteEncargado',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='numeroEscala',
        ),
        migrations.AddField(
            model_name='estadocamarote',
            name='descripcionEstadoCamarote',
            field=models.TextField(default=1, verbose_name='Descripción del Estado del Camarote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recorrido',
            name='numeroEscala',
            field=models.IntegerField(default=1, verbose_name='Numero Escala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacamarote',
            name='encargadoReservado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seastar.tripulante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadocamarote',
            name='nombreEstadoCamarote',
            field=models.CharField(max_length=255, verbose_name='Estado del Camarote'),
        ),
    ]
