# Generated by Django 4.2.5 on 2023-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0008_rename_camarotesreservado_reservacamarote_camarotereservado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocamarote',
            name='camaroteOcupado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
