# Generated by Django 4.2.5 on 2023-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0010_remove_estadocamarote_camaroteocupado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudviaje',
            name='pasajero',
        ),
        migrations.AddField(
            model_name='solicitudviaje',
            name='pasajero',
            field=models.ManyToManyField(to='seastar.pasajero'),
        ),
    ]
