# Generated by Django 4.2.5 on 2023-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0013_tipodocumento_alter_pasajero_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='tipo_documento',
            field=models.CharField(max_length=100, verbose_name='Tipo de Documento'),
        ),
    ]
