# Generated by Django 4.2.5 on 2023-10-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0014_alter_pasajero_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.tipodocumento'),
        ),
    ]
