# Generated by Django 4.2.5 on 2023-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0018_remove_pasajero_camarote_alojado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudViaje',
        ),
    ]
