# Generated by Django 4.2.5 on 2023-11-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0019_delete_solicitudviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacamarote',
            name='recorridoReservado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seastar.recorrido'),
            preserve_default=False,
        ),
    ]
