# Generated by Django 4.2.5 on 2023-11-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0021_camarote_navioubicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacamarote',
            name='encargadoReservado',
        ),
    ]
