# Generated by Django 4.2.5 on 2023-11-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0023_remove_recorrido_listapasajeros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='username',
            field=models.CharField(default='default', max_length=50, verbose_name='Usuario'),
        ),
    ]
