# Generated by Django 4.2.5 on 2023-12-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0024_pasajero_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tripulante',
            name='nombre_tripulante',
        ),
        migrations.AddField(
            model_name='tripulante',
            name='apellido',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido Tripulante'),
        ),
        migrations.AddField(
            model_name='tripulante',
            name='nombre',
            field=models.CharField(default='nombre', max_length=50, verbose_name='Nombre Tripulante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='legajo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Legajo'),
        ),
        migrations.DeleteModel(
            name='HistorialTripulante',
        ),
    ]
