# Generated by Django 4.2.5 on 2023-11-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0025_remove_camarote_navioubicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CambioEstadoNavio',
        ),
        migrations.AddField(
            model_name='navio',
            name='categoriaNavio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seastar.categorianavio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CambioPuerto',
        ),
    ]
