# Generated by Django 4.2.5 on 2023-12-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0025_remove_tripulante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulante',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Tripulante'),
        ),
        migrations.CreateModel(
            name='HistorialTripulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevoNombreJefe', models.CharField(max_length=255, verbose_name='Nuevo Jefe')),
                ('fechaCambio', models.DateTimeField(verbose_name='Fecha del cambio')),
                ('nuevoNavioAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.navio')),
                ('nuevoPuestoTripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.puesto')),
                ('tripulanteCambiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seastar.tripulante')),
            ],
        ),
    ]
