# Generated by Django 4.2.5 on 2023-12-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0026_delete_cambioestadonavio_navio_categorianavio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialTripulante',
        ),
    ]
