erDiagram
    Itinerario ||..|{ Recorrido : "1"
    Itinerario ||..|{ ReservaCamarote : "1"
    Itinerario }|..|{ Puerto : "1"
    Recorrido }|..|| Navio : "1"
    Puesto ||..|{ Tripulante : "1"
    TipoCamarote ||--|{ Camarote : "1"
    Camarote }|--|| EstadoCamarote : "1"
    Navio ||..|{ Cubierta : "1"
    Cubierta ||..|{ Camarote : "1"
    Itinerario }|..|| CategoriaItinerario : "1"
    Pasajero }|..|| Pais : "1"
    Pasajero ||..|{ ReservaCamarote : "1"
    ReservaCamarote }|..|| Camarote : "1"
    Pais ||..|{ Ciudad : "1"
    Navio }|..|| EstadoNavio : "1"
    Navio }|..|| CategoriaNavio : "1"
    Tripulante ||..|{ HistorialTripulante : "1"
    Navio ||..|{ HistorialTripulante : "1"
    Tripulante ||..|{ Tripulante : "1"

Recorrido
    Itinerario {
        - nombreItinerario : string
        - descripcionItinerario : string
        - listaPuertos : Puerto
        - categoriaItinerario : CategoriaItinerario
    }
    Recorrido {
        - numeroEscala : int
        - fechaViaje : datetime
        - duracionViaje : float
        - listaPuertos : Puerto
        - itinerarioRealizado : Itinerario
        - navioDelViaje : Navio
        - listaPasajeros : Pasajero
    }
    Navio {
        - codigoNavio : int
        - nombreNavio : string
        - altura : float
        - eslora : float
        - manga : float
        - desplazamiento : float
        - autonomiaViaje : float
        - cantidadCamarotes : int
        - maxCantidadPasajeros : int
        - cantidadMotores : int
        - cantidadTripulantes : int
    }
    Cubierta {
        - numeroCubierta : int
        - ubicacionCubierta : string
        - descripcionCubierta : string
        - encargado : Tripulante
        - navioUbicado : Navio
    }
    Camarote {
        - ubicacionCamarote : string
        - numeroCamarote : int
        - ubicacionCamarote : int
        - estadoCamarote : EstadoCamarote
        - cubiertaUbicada : Cubierta
    }
    Tripulante {
        - nombreTripulante : string
        - legajo : string
        - navio_asignado : Navio
        - puesto_tripulante : Puesto
        - nombreJefe : string
    }
    HistorialTripulante {
        - tripulanteCambiado : Tripulante 
        - nuevoPuestoTripulante : Puesto
        - nuevoNombreJefe : String
        - nuevoNavioAsignado : Navio
        - fechaCambio : datetime
    }
    Puesto {
        - nombrePuesto : string
        - descripcionPuesto : string
    }
    Puerto {
        - nombrePuerto : string
        - descripcionPuerto : string
    }
    Pasajero {
        - tipoDocumento : string
        - numeroDocumento : int
        - nombre : string
        - username : String
        - pais_origen : Pais
        - ciudad_origen : Ciudad
    }
    EstadoNavio {
        - nombreEstadoNavio : string
        - descripcionEstadoNavio : string
    }
    EstadoCamarote {
        - nombreEstadoCamarote : string
        - descripcionEstadoCamarote : string
    }
    ReservaCamarote {
        - fechaReserva : datetime
        - listaPasajeros : Pasajero
        - camaroteReservado : Camarote
        - recorridoReservado : Recorrido
    }
    TipoCamarote {
        - nombreTipoCamarote : string
        - descripcionTipoCamarote : string
    }
    CambioEstadoNavio {
        - nombreEstadoNavio : string
        - fechaCambioEstado : datetime
    }
    CategoriaNavio {
        - nombreCategoria : string
        - descripcionCategoria : string
    }
    CategoriaItinerario {
        - nombreCategoria : string
        - descripcionCategoria : string
    }
    Pais {
        - nombrePais : string
        - descripcionPais : string
        - moneda : string
        - idioma : string
    }
    Ciudad {
        - nombreCiudad : string
        - descripcionCiudad : string
    }


