# Generated by Django 4.2.4 on 2023-08-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoNavio', models.IntegerField(verbose_name='Código')),
                ('nombreNavio', models.CharField(max_length=50, verbose_name='Nombre')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('eslora', models.FloatField(verbose_name='Eslora')),
                ('manga', models.FloatField(verbose_name='Manga')),
                ('desplazamiento', models.FloatField(verbose_name='Desplazamiento')),
                ('autonomiaViaje', models.FloatField(verbose_name='Autonomía de Viajes')),
                ('cantidadCamarotes', models.IntegerField(verbose_name='Cantidad de Camarotes')),
                ('maxCantidadPasajeros', models.IntegerField(verbose_name='Cantidad máxima de Pasajeros')),
                ('cantidadMotores', models.IntegerField(verbose_name='Cantidad de Motores')),
                ('cantidadTripulantes', models.IntegerField(verbose_name='Cantidad de Tripulantes')),
            ],
        ),
    ]
